### ISSUE TITLE
Repeater not working with Shop Isle

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pirate-switch#16]
http://prntscr.com/f2mppo

**Comment by abaicus** [comment]
The repeater on shopisle is the old version. I've been putting off updating it because it's really different from what we have in other themes and the icons font is a different one. Should we update the repeater?

**Comment by rodica-andronache** [comment]
@abaicus you can investigate how this would influence the current users. If there would not be problems on update, yeah, maybe would be a good idea to update the repeater. And for the fonts, can't we change the repeater to have the current icons from the theme ? Or just replace it with the new one ( with font awesome , which some users already asked for ) and have a way to use the old fonts just for the already set up options?

**Comment by abaicus** [comment]
It would be really hard to make it compatible with both. I wouldn't go through that rabbit hole further. I'd much rather make it compatible with what we currently have. Plus that means loading more resources and css files.

**Comment by ineagu** [comment]
@rodica-andronache let's not spend too much time on this, the initial goal is to test it with zerif and see if it helps or not and how much.

It doesn't need to work automatically for all the themes if we can easily configure it, of course is not a bad idea to keep things standard across themes, but this is another discussion, for the  switcher isn't really required

**Comment by abaicus** [comment]
So for now are we postponing this?

**Comment by ineagu** [comment]
yep, just get it live for some big themes and see how it goes, I think @dascalescuro has a task for an a/b test.
