### ISSUE TITLE
improvements based on device

### ISSUE THREAD

**Issue by dascalescuro** [Codeinwp/pirate-switch#31]
@abaicus could you please further improve the switcher with:

- [x] automatically open the switcher when on desktop devices -> https://prntscr.com/hdtav6
- [x] on smaller devices (probably under 1024px ) keep it closed ->  http://prntscr.com/hdtcbe
- [x] on phones we can continue hide it

CC: @ineagu

**Comment by ineagu** [comment]
ping.
