### ISSUE TITLE
remember state

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/pirate-switch#32]
@abaicus if I am on hestia home on demo and I close the switcher, when I go on contact page, the switcher will open by default.

We should use a cookie or somethign and remember the switcher state across pages, even on the next visit of the user. Now is pretty annoying.

**Comment by ineagu** [comment]
@abaicus maybe you can take a look at this soon, it might affect conversions and it should be a small thing :D

**Comment by abaicus** [comment]
Done 👍 .
